pipeline {
  agent { label "linux" }
  stages {
    stage("build") {
      steps {
        sh """
          docker build -t Trabalho52 .
        """
      }
    }
    stage("run") {
      steps {
        sh """
          docker run --rm Trabalho52
        """
      }
    }
  }
}


